version: '3.8'

services:
  # Your Next.js Application
  app:
    build: .
    container_name: voting_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/voting_db
    depends_on:
      - mongo

  # The Database
  mongo:
    image: mongo
    container_name: voting_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: